title: Li Yin
author: Li Yin
email: liyin199102@gmail.com
# social links
twitter_username: LiSulimowicz
github_username:  liyin2015
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: liyinscience
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

description: >
  Every big acchievement is a series of small meaningful daily events!


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

#plugins:
#  - jekyll-archives
#  - jekyll-paginate
#  - jekyll-sitemap

#permalink: /:year/:month/:day/:title/
#paginate_path: /posts/:num/
#paginate: 5

#jekyll-archives:
#  enabled:
#    - categories
#    - tags
#  layout: category_archives
#  permalinks:
#    category: /categories/:name/
#    tag: /tags/:name/
